# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.upload_controller_api import UploadControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUploadControllerApi(unittest.TestCase):
    """UploadControllerApi unit test stubs"""

    def setUp(self):
        self.api = UploadControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_file(self):
        """Test case for upload_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
