# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.browse_controller_api import BrowseControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestBrowseControllerApi(unittest.TestCase):
    """BrowseControllerApi unit test stubs"""

    def setUp(self):
        self.api = BrowseControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_browse_folder(self):
        """Test case for browse_folder

        """
        pass


if __name__ == '__main__':
    unittest.main()
