# coding: utf-8

"""
    OpenAPI definition

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.delete_controller_api import DeleteControllerApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDeleteControllerApi(unittest.TestCase):
    """DeleteControllerApi unit test stubs"""

    def setUp(self):
        self.api = DeleteControllerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_file(self):
        """Test case for delete_file

        """
        pass


if __name__ == '__main__':
    unittest.main()
